//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimeListApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimeList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnimeList()
        {
            this.Animes = new HashSet<Anime>();
        }
    
        public int Id { get; set; }
        public int AnimeID { get; set; }
        public int StatusID { get; set; }
        public int NoteID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anime> Animes { get; set; }
        public virtual AnimeData AnimeData { get; set; }
        public virtual Note Note { get; set; }
        public virtual Status Status { get; set; }
    }
}
